
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(1, 'INFOSYS', 'Infy', 1358);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(2, 'WIPRO', 'Wip', 1199);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(3, 'Jaypee.', 'JP', 1295);


insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(4, 'Tata Consultancy Services', 'TCS', 1108);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(5, 'ACC Ltd.', 'ACC', 1358);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(6, 'Adani Enterprises Lt.', 'ADANIENT', 199);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(7, 'Ambuja Cements Ltd.', 'ABIRLANUVO', 795);


insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(8, 'Andhra Bank', 'ANDHRABANK', 108);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(9, 'Ashok Leyland Ltd.', 'ASHOKLEY', 24);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(10, 'Asian Paints Ltd.', 'ASIANPAINT', 3895);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(11, 'Axis Bank Ltd.', 'AXISBANK', 1044);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(12, 'Bajaj Auto Ltd.', 'BAJAJ-AUTO', 1791);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(13, 'Bank of Baroda', 'BANKBARODA', 747);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(14, 'Bank of India', 'BANKINDIA', 286);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(15, 'Bharat Electronics L...', 'BEL', 1208);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(16, 'Bharat Forge Ltd.', 'BHARATFORG', 294);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(17, 'Bharat Heavy Electri...', 'BHEL', 216);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(18, 'Bharat Petroleum Cor...', 'BPCL', 345);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(19, 'Bharti Airtel Ltd.', 'BHARATARTL', 268);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(20, 'Biocon Ltd.', 'BIOCON', 273);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(21, 'Bosch Ltd.', 'BOSCHLTD', 8487);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(22, 'Cairn India Ltd.', 'CAIRN', 341);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(23, 'Canara Bank', 'CANBK', 405);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(24, 'Cipla Ltd.', 'CIPLA', 360);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(25, 'Coal India Ltd', 'CIL', 365);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(26, 'Colgate Palmolive (I...', 'COLPAL', 1196);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(27, 'Container Corporatio...', 'CONCOR', 942);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(28, 'Crompton Greaves Ltd...', 'CROMPGREAV', 112);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(29, 'Cummins India Ltd.', 'CUMMINSIND', 477);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(30, 'Dabur India Ltd.', 'DABUR', 124);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(31, 'Divis Laboratories', 'DIVISLAB', 1071);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(32, 'DLF Ltd.', 'DLF', 230);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(33, 'Dr. Reddys Laborato...', 'DRREDDY', 1665);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(34, 'Exide Industries Ltd...', 'EXIDEIND', 146);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(35, 'Federal Bank Ltd.', 'FEDERALBNK', 423);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(36, 'GAIL (India) Ltd.', 'GAIL', 374);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(37, 'GlaxoSmithkline Cons...', 'GSKCONS', 2910);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(38, 'Glaxosmithkline Phar...', 'GLAXO', 1985);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(39, 'Glenmark Pharmaceuti...', 'GLENMARK', 418);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(41, 'GMR Infrastructure L...', 'GMRINFRA', 23);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(42, 'Grasim Industries Lt...', 'GRASIM', 3110);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(43, 'HCL Technologies Ltd...', 'HCLTECH', 568);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(44, 'HDFC Bank Ltd.', 'HDFCBANK', 606);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(45, 'Hero Honda Motors Lt...', 'HEROHONDA', 1900);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(46, 'Hindalco Industries ...', 'HINDALCO', 113);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(47, 'Hindustan Petroleum ...', 'HINDPETRO', 296);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(48, 'Hindustan Unilever L...', 'HINDUNILVR', 527);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(49, 'Housing Development ...', 'HDFC', 760);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(50, 'I T C Ltd.', 'ITC', 256);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(51, 'ICICI Bank Ltd.', 'ICICIBANK', 1022);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(52, 'Idea Cellular Ltd.', 'IDEA', 88);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(53, 'Indian Hotels Co. Lt...', 'INDHOTEL', 61);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(54, 'IndusInd Bank Ltd.', 'INDUSINDBK', 331);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(55, 'Industrial Developme...', 'IDBI', 96);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(56, 'Indica tec pvt ltd...', 'INDTCH', 2617);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(57, 'Infrastructure Devel...', 'IDFC', 146);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(58, 'Jaiprakash Associate...', 'JPASSOCIAT', 79);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(59, 'Jindal Steel & Power...', 'JINDALSTEL', 400);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(60, 'JSW Steel Ltd.', 'JSWSTEEL', 706);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(61, 'Kotak Mahindra Bank ...', 'KOTAKBANK', 602);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(62, 'Larsen & Toubro Ltd.', 'LT', 1521);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(63, 'LIC Housing Finance ...', 'LICHSGFIN', 258);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(64, 'Lupin Ltd.', 'LUPIN', 579);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(65, 'Mahindra & Mahindra ...', 'M&M', 784);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(66, 'Maruti Suzuki India ...', 'MARUTI', 1282);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(67, 'MphasiS Ltd.', 'MPHASIS', 389);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(68, 'NTPC Ltd.', 'NTPC', 164);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(69, 'Oil & Natural Gas Co...', 'ONGC', 285);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(70, 'Oracle Financial Ser...', 'OFSS', 2957);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(71, 'Petronet LNG Ltd.', 'PETRONET', 168);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(72, 'Power Finance Corpor...', 'PFC', 195);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(73, 'Power Grid Corporati...', 'POWERGRID', 117);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(74, 'Punjab National Bank', 'PNB', 795);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(75, 'Ranbaxy Laboratories...', 'RANBAXY', 529);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(76, 'Reliance Capital Ltd...', 'RELCAPITAL', 362);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(77, 'Reliance Communicati...', 'RCOM', 58);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(78, 'Reliance Industries ...', 'RELIANCE', 833);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(79, 'Reliance Infrastruct...', 'RELINFRA', 496);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(80, 'Reliance Power Ltd.', 'RPOWER', 89);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(81, 'Rural Electrificatio...', 'RECLTD', 216);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(82, 'Sesa Goa Ltd.', 'SESAGOA', 171);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(83, 'Shriram Transport Fi...', 'SRTRANSFIN', 618);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(84, 'Siemens Ltd.', 'SIEMENS', 682);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(85, 'State Bank of India', 'SBIN', 2123);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(86, 'Steel Authority of I...', 'SAIL', 86);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(87, 'Sterlite Industries ...', 'STER', 99);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(88, 'Sun Pharmaceutical I...', 'SUNPHARMA', 671);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(89, 'Tata Chemicals Ltd.', 'TATACHEM', 315);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(90, 'Tata Software Ser...', 'TSS', 1322);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(91, 'Tata Motors Ltd.', 'TATAMOTORS', 272);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(92, 'Tata Power Co. Ltd.', 'TATAPOWER', 99);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(93, 'Tata Steel Ltd.', 'TATASTEEL', 393);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(94, 'Tech Mahindra Ltd.', 'TECHM', 899);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(95, 'Titan Industries Ltd...', 'TITAN', 242);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(96, 'Torrent Power Ltd.', 'TORNTPOWER', 158);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(97, 'UltraTech Cement Ltd...', 'ULTRACEMCO', 1837);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(98, 'Union Bank of India', 'UNIONBANK', 195);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(99, 'United Phosphorus Lt...', 'UNIPHOS', 128);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(100, 'United Spirits Ltd.', 'MCDOWELL-N', 942);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(101, 'Wipro BPO Ltd.', 'WIPRO', 373);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(102, 'Yes Bank Ltd.', 'YESBANK', 363);
insert into `stock_master` (`stock_id`, `name`, `symbol`, `price`) values(103, 'Zee Entertainment En...', 'ZEEL', 184);